language: haskell
before_install:
  - cabal update
  - travis/cabal-apt-install $mode

install:
  - cabal configure -flib-Werror $mode
  - cabal build

env:
  - mode=""
  # - mode="--enable-tests" script="cabal test --show-details=always"